"""migration add of log table

Revision ID: 4432bf9127a3
Revises: ef49a4906333
Create Date: 2025-11-25 20:02:37.964441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4432bf9127a3'
down_revision = 'ef49a4906333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=15), nullable=False),
    sa.Column('old_values', mysql.JSON(), nullable=False),
    sa.Column('new_values', mysql.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
