"""Fix in record_id

Revision ID: a0ff4767f8bc
Revises: aedf9c2ffac5
Create Date: 2025-11-28 12:52:20.337618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0ff4767f8bc'
down_revision = 'aedf9c2ffac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.String(length=26),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
