"""Change id user to ulid 
Criado e revisado por Daniel Quintela

Revision ID: aedf9c2ffac5
Revises: fc1681304af4
Create Date: 2025-11-28 11:30:10.208780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aedf9c2ffac5'
down_revision = 'fc1681304af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('products_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['categories_id'], ['id'])
        batch_op.create_foreign_key(None, 'producers', ['producer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=26),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_ibfk_2'), 'producers', ['producer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('products_ibfk_1'), 'categories', ['categories_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
