"""dq migration testing id table promotion
Criado e revisado por Daniel Quintela - dq

Revision ID: fe0a64bb9849
Revises: 5d63e59018e4
Create Date: 2025-11-27 20:26:38.098933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe0a64bb9849'
down_revision = '5d63e59018e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=26),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
